// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Sep 23 10:12:34 2006
#ifndef WX3DMODELDIALOG_H
#define WX3DMODELDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

#include "Vector.hh"

class wx3DModelDialog: public wxDialog {
public:
  // begin wxGlade: wx3DModelDialog::ids
  // end wxGlade

  wx3DModelDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
  // begin wxGlade: wx3DModelDialog::methods
  void set_properties();
  void do_layout();
  // end wxGlade

protected:
  // begin wxGlade: wx3DModelDialog::attributes
  wxStaticText* lb3DModelType;
  wxComboBox* cmbbx3DModelType;
  wxStaticText* lb3DModelID;
  wxTextCtrl* txt3DModelID;
  wxStaticText* lbPositionX;
  wxTextCtrl* txtPositionX;
  wxStaticText* lbPositionY;
  wxTextCtrl* txtPositionY;
  wxStaticText* lbPositionZ;
  wxTextCtrl* txtPositionZ;

  wxButton* btAdd;
  wxButton* btCancel;
  // end wxGlade

public: 
  wxString Get3DModelType();
  GzVector Get3DModelPosition();
  wxString Get3DModelID();

  bool IsButtonAddPressed();

private:
  bool bButtonAddPressed;
  void On_BtAdd_Clicked(wxCommandEvent& e);
  void On_BtCancel_Clicked(wxCommandEvent& e);

}; // wxGlade: end class

#endif // WX3DMODELDIALOG_H


