// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Dec 01 10:44:25 2006

#ifndef WXCONFIGURATIONPANEL_H
#define WXCONFIGURATIONPANEL_H

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

#include "ConfigurationFile.h"
#include <vector>

using namespace std;

class wxConfigurationPanel: public wxPanel 
{
public:
    // begin wxGlade: wxConfigurationPanel::ids
    // end wxGlade
    wxConfigurationPanel(wxWindow* parent, int id,ConfigurationFile * configurationFile);
    ConfigurationFile * GetConfigurationFile();

private:
    ConfigurationFile * configurationFile;
    // begin wxGlade: wxConfigurationPanel::methods
    void set_properties();
    void do_layout();
    // end wxGlade

public:
    // begin wxGlade: wxConfigurationPanel::attributes
    wxStaticText* lbPortNumber;
    wxTextCtrl*   txtPortNumber;
    wxStaticText* lbServerDriver;
    wxGrid* gridServerDriver;
    wxButton* btEditServerDriver;
    wxStaticText* lbModelDriver;
    wxGrid* gridModelDriver;
    wxButton* btAddModelDriver;
    wxButton* btEditModelDriver;
    wxButton* btRemoveModelDriver;
    // end wxGlade

}; // wxGlade: end class

#endif // WXCONFIGURATIONPANEL_H

