// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Dec 03 23:00:07 2006

#include "wxIRCEConfigurationDialog.h"


wxIRCEConfigurationDialog::wxIRCEConfigurationDialog(wxWindow* parent,wxWindowID id,const wxString& title):
    wxDialog(parent, id, title) 
{
    // begin wxGlade: wxIRCEConfigurationDialog::wxIRCEConfigurationDialog
    lbPlayerPath = new wxStaticText(this, -1, wxT("Caminho do Player"));
    txtPlayerPath = new wxTextCtrl(this, -1, wxT(""));
    lbGazeboPath = new wxStaticText(this, -1, wxT("Caminho do Gazebo"));
    txtGazeboPath = new wxTextCtrl(this, -1, wxT(""));
    lbCPPCompilerPath = new wxStaticText(this, -1, wxT("Caminho do Compilador C++"));
    txtCPPCompilerPath = new wxTextCtrl(this, -1, wxT(""));
    lbPlayerHeaderPath = new wxStaticText(this, -1, wxT("Caminho dos cabecalhos do Player"));
    txtPlayerHeaderPath = new wxTextCtrl(this, -1, wxT(""));
    lbPlayerLibPath = new wxStaticText(this, -1, wxT("Caminho das libs do Player"));
    txtPlayerLibPath = new wxTextCtrl(this, -1, wxT(""));
    btOk = new wxButton(this, id+1, wxT("Ok"));
    btCancel = new wxButton(this, id+2, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade

    wxEvtHandler::Connect(id+1,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxIRCEConfigurationDialog::On_BtOk_Clicked );
    wxEvtHandler::Connect(id+2,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxIRCEConfigurationDialog::On_BtCancel_Clicked );  

}


void wxIRCEConfigurationDialog::set_properties()
{
    // begin wxGlade: wxIRCEConfigurationDialog::set_properties
    SetTitle(wxT("Simulation Configuration Dialog"));
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
    txtPlayerPath->SetSize(wxSize(200, 21));
    txtGazeboPath->SetSize(wxSize(200, 21));
    txtCPPCompilerPath->SetSize(wxSize(200, 21));
    txtPlayerHeaderPath->SetSize(wxSize(200, 21));
    txtPlayerLibPath->SetSize(wxSize(200, 21));
    // end wxGlade
}


void wxIRCEConfigurationDialog::do_layout()
{
    // begin wxGlade: wxIRCEConfigurationDialog::do_layout
    wxGridSizer* sizerMain = new wxGridSizer(6, 2, 0, 0);
    sizerMain->Add(lbPlayerPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtPlayerPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbGazeboPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtGazeboPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbCPPCompilerPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtCPPCompilerPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbPlayerHeaderPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtPlayerHeaderPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbPlayerLibPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtPlayerLibPath, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(btOk, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(btCancel, 0, wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(sizerMain);
    sizerMain->Fit(this);
    sizerMain->SetSizeHints(this);
    Layout();
    // end wxGlade
}

void wxIRCEConfigurationDialog::On_BtOk_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetModal(wxID_OK);
}

void wxIRCEConfigurationDialog::On_BtCancel_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetModal(wxID_CANCEL);
}
