
// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Jul 09 19:43:48 2006

#include "wxIRCEMenuBar.h"


wxIRCEMenuBar::wxIRCEMenuBar():
    wxMenuBar()
{
    // begin wxGlade: wxIRCEMenuBar::wxIRCEMenuBar

    set_properties();
    do_layout();
    // end wxGlade
}


void wxIRCEMenuBar::set_properties()
{
    // begin wxGlade: wxIRCEMenuBar::set_properties

    //wxMenu* imenuFile = new wxMenu();    
    //imenuFile->Append(3, wxT("New World File"), wxT(""), wxITEM_NORMAL);
    //imenuFile->Append(4, wxT("Load World File"), wxT(""), wxITEM_NORMAL);
    //imenuFile->Append(5, wxT("Exit"), wxT(""), wxITEM_NORMAL);
    //Append(imenuFile, wxT("File"));
    //wxMenu* imenuHelp = new wxMenu();
    //Append(imenuHelp, wxT("Help"));

    // end wxGlade   
    
    wxMenu* imenuProject = new wxMenu();    
    imenuProject->Append(NEW_PROJECT_MENU, wxT("New Project"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(EDIT_PROJECT_MENU, wxT("Edit Project"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(LOAD_PROJECT_MENU, wxT("Load Project"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(SAVE_PROJECT_MENU, wxT("Save Project"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(SIMULATE_PROJECT_MENU, wxT("Simulate"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(TRANSFER_CONTROL_MENU, wxT("Transfer Controls"), wxT(""), wxITEM_NORMAL);
    imenuProject->Append(EXIT_MENU, wxT("Exit"), wxT(""), wxITEM_NORMAL);
    Append(imenuProject, wxT("Project"));

    wxMenu* imenuWorld = new wxMenu();
    imenuWorld->Append(NEW_WORLD_FILE, wxT("New World File"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(CLEAN_VIRTUAL_WORLD, wxT("Clean World"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(LOAD_WORLD_FILE, wxT("Load World File"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(SAVE_WORLD_FILE, wxT("Save World File"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(ADD_3D_MODEL, wxT("Add 3D Model"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(REMOVE_3D_MODEL, wxT("Remove 3D Model"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(SELECT_3D_MODEL, wxT("Select 3D Model"), wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(ADD_CHILD_MODEL,   wxT("Add Child Model"),wxT(""), wxITEM_NORMAL);
    imenuWorld->Append(REMOVE_CHILD_MODEL,wxT("Remove Child Model"),wxT(""),wxITEM_NORMAL);
    Append(imenuWorld, wxT("Virtual World"));

    wxMenu* imenuControl = new wxMenu();
    imenuControl->Append(NEW_CONTROL_PROGRAM, wxT("New Control Program"), wxT(""), wxITEM_NORMAL);
    imenuControl->Append(LOAD_CONTROL_PROGRAM, wxT("Load Control Program"), wxT(""), wxITEM_NORMAL);
    imenuControl->Append(SAVE_CONTROL_PROGRAM, wxT("Save Control Program"), wxT(""), wxITEM_NORMAL);
    imenuControl->Append(REMOVE_CONTROL_PROGRAM, wxT("Remove Control Program"), wxT(""), wxITEM_NORMAL);
    imenuControl->Append(COMPILE_CONTROL_PROGRAM, wxT("Compile Control Program"), wxT(""), wxITEM_NORMAL);
    Append(imenuControl, wxT("Control Programs"));

    wxMenu* imenuConfiguration = new wxMenu();
    imenuConfiguration->Append(NEW_CONFIGURATION_FILE, wxT("New Configuration File"), wxT(""), wxITEM_NORMAL);
    imenuConfiguration->Append(LOAD_CONFIGURATION_FILE, wxT("Load Configuration File"), wxT(""), wxITEM_NORMAL);
    imenuConfiguration->Append(SAVE_CONFIGURATION_FILE, wxT("Save Configuration File"), wxT(""), wxITEM_NORMAL);
    imenuConfiguration->Append(REMOVE_CONFIGURATION_FILE, wxT("Remove Configuration File"), wxT(""), wxITEM_NORMAL);
    Append(imenuConfiguration, wxT("Configuration Files"));
    
    wxMenu* imenuHelp = new wxMenu();
    imenuHelp->Append(ABOUT_MENU, wxT("About"), wxT(""), wxITEM_NORMAL);
    Append(imenuHelp, wxT("Help"));   
}


void wxIRCEMenuBar::do_layout()
{
    // begin wxGlade: wxIRCEMenuBar::do_layout
    // end wxGlade
}


void wxIRCEMenuBar::SetState(enum wxIRCEMenuBar_States state)
{  
  bool bEnable_Menu_New_Project  = false;
  bool bEnable_Menu_Edit_Project = false;
  bool bEnable_Menu_Load_Project = false;
  bool bEnable_Menu_Save_Project = false;
  bool bEnable_Menu_Simulate     = false;
  bool bEnable_Menu_Transfer_Control = false;
  bool bEnable_Menu_Exit             = false;
  
  bool bEnable_Menu_New_World_File   = false;
  bool bEnable_Menu_Clean_Virtual_World = false;
  bool bEnable_Menu_Load_World_File  = false;
  bool bEnable_Menu_Save_World_File  = false;
  bool bEnable_Menu_Add_3D_Model     = false;
  bool bEnable_Menu_Remove_3D_Model  = false;
  bool bEnable_Menu_Select_3D_Model  = false;
  bool bEnable_Menu_Add_Child_Model  = false;
  bool bEnable_Menu_Remove_Child_Model = false;

  bool bEnable_Menu_New_Control_Program  = false;
  bool bEnable_Menu_Load_Control_Program = false;
  bool bEnable_Menu_Save_Control_Program = false;
  bool bEnable_Menu_Remove_Control_Program = false;
  bool bEnable_Menu_Compile_Control_Program = false;

  bool bEnable_Menu_New_Configuration_File  = false;
  bool bEnable_Menu_Load_Configuration_File = false;
  bool bEnable_Menu_Save_Configuration_File = false;
  bool bEnable_Menu_Remove_Configuration_File = false;

  switch(state)
  {

  case NO_PROJECT_CREATED:
    
    bEnable_Menu_New_Project      = true;
    bEnable_Menu_Edit_Project     = false;
    bEnable_Menu_Load_Project     = true;
    bEnable_Menu_Save_Project     = false;
    bEnable_Menu_Simulate         = false;
    bEnable_Menu_Transfer_Control = false;
    bEnable_Menu_Exit             = true;

    bEnable_Menu_New_World_File   = false;
    bEnable_Menu_Clean_Virtual_World = false;
    bEnable_Menu_Load_World_File  = false;
    bEnable_Menu_Save_World_File  = false;
    bEnable_Menu_Add_3D_Model     = false;
    bEnable_Menu_Remove_3D_Model  = false;
    bEnable_Menu_Select_3D_Model  = false;
    bEnable_Menu_Add_Child_Model  = false;
    bEnable_Menu_Remove_Child_Model = false;

    bEnable_Menu_New_Control_Program  = false;
    bEnable_Menu_Load_Control_Program = false;
    bEnable_Menu_Save_Control_Program = false;
    bEnable_Menu_Remove_Control_Program = false;
    bEnable_Menu_Compile_Control_Program = false;   

    bEnable_Menu_New_Configuration_File  = false;
    bEnable_Menu_Load_Configuration_File = false;
    bEnable_Menu_Save_Configuration_File = false;
    bEnable_Menu_Remove_Configuration_File = false;

    break;

  case PROJECT_CREATED:

    bEnable_Menu_New_Project      = true;
    bEnable_Menu_Edit_Project     = false;
    bEnable_Menu_Load_Project     = true;
    bEnable_Menu_Save_Project     = false;
    bEnable_Menu_Simulate         = false;
    bEnable_Menu_Transfer_Control = false;
    bEnable_Menu_Exit             = true;

    bEnable_Menu_New_World_File   = true;
    bEnable_Menu_Clean_Virtual_World = false;
    bEnable_Menu_Load_World_File  = true;
    bEnable_Menu_Save_World_File  = false;
    bEnable_Menu_Add_3D_Model     = false;
    bEnable_Menu_Remove_3D_Model  = false;
    bEnable_Menu_Select_3D_Model  = false;
    bEnable_Menu_Add_Child_Model  = false;
    bEnable_Menu_Remove_Child_Model = false;

    bEnable_Menu_New_Control_Program  = true;
    bEnable_Menu_Load_Control_Program = true;
    bEnable_Menu_Save_Control_Program = false;
    bEnable_Menu_Remove_Control_Program = false;
    bEnable_Menu_Compile_Control_Program = false;  

    bEnable_Menu_New_Configuration_File  = true;
    bEnable_Menu_Load_Configuration_File = true;
    bEnable_Menu_Save_Configuration_File = false;
    bEnable_Menu_Remove_Configuration_File = false;
 
    break;

  case CONFIGURATION_SELECTED:

    bEnable_Menu_New_Project      = true;
    bEnable_Menu_Edit_Project     = true;
    bEnable_Menu_Load_Project     = true;
    bEnable_Menu_Save_Project     = true;
    bEnable_Menu_Simulate         = true;
    bEnable_Menu_Transfer_Control = true;
    bEnable_Menu_Exit             = true;

    bEnable_Menu_New_World_File   = true;
    bEnable_Menu_Clean_Virtual_World = false;
    bEnable_Menu_Load_World_File  = true;
    bEnable_Menu_Save_World_File  = false;
    bEnable_Menu_Add_3D_Model     = false;
    bEnable_Menu_Remove_3D_Model  = false;
    bEnable_Menu_Select_3D_Model  = false;
    bEnable_Menu_Add_Child_Model  = false;
    bEnable_Menu_Remove_Child_Model = false;

    bEnable_Menu_New_Control_Program  = true;
    bEnable_Menu_Load_Control_Program = true;
    bEnable_Menu_Save_Control_Program = false;
    bEnable_Menu_Remove_Control_Program = false;
    bEnable_Menu_Compile_Control_Program = false;   

    bEnable_Menu_New_Configuration_File  = true;
    bEnable_Menu_Load_Configuration_File = true;
    bEnable_Menu_Save_Configuration_File = true;
    bEnable_Menu_Remove_Configuration_File = true; 

    break;
  
  case VIRTUAL_WORLD_SELECTED:

    bEnable_Menu_New_Project      = true;
    bEnable_Menu_Edit_Project     = true;
    bEnable_Menu_Load_Project     = true;
    bEnable_Menu_Save_Project     = true;
    bEnable_Menu_Simulate         = true;
    bEnable_Menu_Transfer_Control = true;
    bEnable_Menu_Exit             = true;

    bEnable_Menu_New_World_File   = true;
    bEnable_Menu_Clean_Virtual_World = true;
    bEnable_Menu_Load_World_File  = true;
    bEnable_Menu_Save_World_File  = true;
    bEnable_Menu_Add_3D_Model     = true;
    bEnable_Menu_Remove_3D_Model  = true;
    bEnable_Menu_Select_3D_Model  = true;
    bEnable_Menu_Add_Child_Model  = true;
    bEnable_Menu_Remove_Child_Model = true;

    bEnable_Menu_New_Control_Program  = true;
    bEnable_Menu_Load_Control_Program = true;
    bEnable_Menu_Save_Control_Program = false;
    bEnable_Menu_Remove_Control_Program = false;
    bEnable_Menu_Compile_Control_Program = false;  

    bEnable_Menu_New_Configuration_File  = true;
    bEnable_Menu_Load_Configuration_File = true;
    bEnable_Menu_Save_Configuration_File = false;
    bEnable_Menu_Remove_Configuration_File = false;

    break;

  case CLIENT_CONTROL_SELECTED:

    bEnable_Menu_New_Project      = true;
    bEnable_Menu_Edit_Project     = true;
    bEnable_Menu_Load_Project     = true;
    bEnable_Menu_Save_Project     = true;
    bEnable_Menu_Simulate         = true;
    bEnable_Menu_Transfer_Control = true;
    bEnable_Menu_Exit             = true;

    bEnable_Menu_New_World_File   = true;
    bEnable_Menu_Clean_Virtual_World = false;
    bEnable_Menu_Load_World_File  = true;
    bEnable_Menu_Save_World_File  = false;
    bEnable_Menu_Add_3D_Model     = false;
    bEnable_Menu_Remove_3D_Model  = false;
    bEnable_Menu_Select_3D_Model  = false;
    bEnable_Menu_Add_Child_Model  = false;
    bEnable_Menu_Remove_Child_Model = false;   

    bEnable_Menu_New_Control_Program  = true;
    bEnable_Menu_Load_Control_Program = true;
    bEnable_Menu_Save_Control_Program = true;
    bEnable_Menu_Remove_Control_Program = true;
    bEnable_Menu_Compile_Control_Program = true;   

    bEnable_Menu_New_Configuration_File  = true;
    bEnable_Menu_Load_Configuration_File = true;
    bEnable_Menu_Save_Configuration_File = false;
    bEnable_Menu_Remove_Configuration_File = false; 
   
    break;
  
  }

  // Faz as mudan�as no menu

  // PROJECT PROGRAM MENU
  // NEW_PROJECT
  this->GetMenu(0)->GetMenuItems().Item(0)->GetData()->Enable(bEnable_Menu_New_Project);
  // EDIT_PROJECT
  this->GetMenu(0)->GetMenuItems().Item(1)->GetData()->Enable(bEnable_Menu_Edit_Project);
  // LOAD_PROJECT
  this->GetMenu(0)->GetMenuItems().Item(2)->GetData()->Enable(bEnable_Menu_Load_Project);
  // SAVE_PROJECT
  this->GetMenu(0)->GetMenuItems().Item(3)->GetData()->Enable(bEnable_Menu_Save_Project);
  // SIMULATE
  this->GetMenu(0)->GetMenuItems().Item(4)->GetData()->Enable(bEnable_Menu_Simulate);
  // TRANSFER_CONTROL
  this->GetMenu(0)->GetMenuItems().Item(5)->GetData()->Enable(bEnable_Menu_Transfer_Control);
  // EXIT
  this->GetMenu(0)->GetMenuItems().Item(6)->GetData()->Enable(bEnable_Menu_Exit);
  
  // VIRTUAL WORLD MENU
  // NEW_WORLD_FILE
  this->GetMenu(1)->GetMenuItems().Item(0)->GetData()->Enable(bEnable_Menu_New_World_File);
  // CLEAN_VIRTUAL_WORLD
  this->GetMenu(1)->GetMenuItems().Item(1)->GetData()->Enable(bEnable_Menu_Clean_Virtual_World);
  // LOAD_WORLD_FILE
  this->GetMenu(1)->GetMenuItems().Item(2)->GetData()->Enable(bEnable_Menu_Load_World_File);
  // SAVE_WORLD_FILE
  this->GetMenu(1)->GetMenuItems().Item(3)->GetData()->Enable(bEnable_Menu_Save_World_File);
  // ADD_3D_MODEL
  this->GetMenu(1)->GetMenuItems().Item(4)->GetData()->Enable(bEnable_Menu_Add_3D_Model);
  // REMOVE_3D_MODEL
  this->GetMenu(1)->GetMenuItems().Item(5)->GetData()->Enable(bEnable_Menu_Remove_3D_Model);
  // SELECT_3D_MODEL
  this->GetMenu(1)->GetMenuItems().Item(6)->GetData()->Enable(bEnable_Menu_Select_3D_Model);
  // ADD_CHILD_MODEL
  this->GetMenu(1)->GetMenuItems().Item(7)->GetData()->Enable(bEnable_Menu_Add_Child_Model);
  // REMOVE_CHILD_MODEL
  this->GetMenu(1)->GetMenuItems().Item(8)->GetData()->Enable(bEnable_Menu_Remove_Child_Model);

  // CLIENT PROGRAM MENU
  // NEW_CONTROL_PROGRAM
  this->GetMenu(2)->GetMenuItems().Item(0)->GetData()->Enable(bEnable_Menu_New_Control_Program);
  // LOAD_CONTROL_PROGRAM
  this->GetMenu(2)->GetMenuItems().Item(1)->GetData()->Enable(bEnable_Menu_Load_Control_Program);
  // SAVE_CONTROL_PROGRAM
  this->GetMenu(2)->GetMenuItems().Item(2)->GetData()->Enable(bEnable_Menu_Save_Control_Program);
  // REMOVE_CONTROL_PROGRAM
  this->GetMenu(2)->GetMenuItems().Item(3)->GetData()->Enable(bEnable_Menu_Remove_Control_Program);
  // COMPILE_CONTROL_PROGRAM
  this->GetMenu(2)->GetMenuItems().Item(4)->GetData()->Enable(bEnable_Menu_Compile_Control_Program);

  // CONFIGURATION PROGRAM MENU
  // NEW_CONFIGURATION_FILE
  this->GetMenu(3)->GetMenuItems().Item(0)->GetData()->Enable(bEnable_Menu_New_Configuration_File);
  // LOAD_CONFIGURATION_FILE
  this->GetMenu(3)->GetMenuItems().Item(1)->GetData()->Enable(bEnable_Menu_Load_Configuration_File);
  // SAVE_CONFIGURATION_FILE
  this->GetMenu(3)->GetMenuItems().Item(2)->GetData()->Enable(bEnable_Menu_Save_Configuration_File);
  // REMOVE_CONFIGURATION_FILE
  this->GetMenu(3)->GetMenuItems().Item(3)->GetData()->Enable(bEnable_Menu_Remove_Configuration_File);

}