// -*- C++ -*- generated by wxGlade 0.4.1 on Fri Jul 28 11:46:36 2006

#ifndef WXIRCEMAINWINDOW_H
#define WXIRCEMAINWINDOW_H

#include <vector>

using namespace std;

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/splitter.h>
#include <wx/notebook.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
// end wxGlade

#include "IRCEProject.h"
#include "PlayerControl.h"

#include "wx3DModelPanel.h"
#include "wxConfigurationPanel.h"
#include "wxClientControlPanel.h"

class wxIRCEMainWindow: public wxFrame {
public:
    // begin wxGlade: wxIRCEMainWindow::ids
    // end wxGlade
    wxIRCEMainWindow(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

    void SetProject(IRCEProject* project);
    void SetVirtualWorld( wxString strWorld );
    void AddControlProgram(PlayerControl* program);
    void RemoveControlProgram(PlayerControl* program);
    void AddConfigurationFile(ConfigurationFile* configuration);
    void RemoveConfigurationFile(ConfigurationFile * configuration);
    int  GetNotebookPage(wxTreeItemId id);
    wxTreeItemId GetVirtualWorldId();
    wxTreeItemId GetConfigurationId();
    wxTreeItemId GetProjectId();

    wx3DModelPanel * Get3DModelPanel();
    wxConfigurationPanel * GetCurrentConfigurationPanel();
    wxClientControlPanel * GetCurrentClientControlPanel();

private:
    vector<wxTreeItemId>   lstControlProgramsId;
    vector<PlayerControl*> lstControlProgram;
    wxTreeItemId         virtualWorldId;
    wxTreeItemId         configurationId;
    wxTreeItemId         projectId;
    vector<wxTreeItemId>   lstConfigurationFilesId;
    vector<ConfigurationFile*> lstConfigurationFiles;    
    // begin wxGlade: wxIRCEMainWindow::methods
    void set_properties();
    void do_layout();
    // end wxGlade

public:
    wxBoxSizer* mainSizer;
    wxBoxSizer* sizerRight;
    wxBoxSizer* sizerModels;
    wxBoxSizer* sizerItems;
    wxGridSizer* sizerProperties;
    wxBoxSizer* sizerLeft;
    wxNotebook* tabModel;
    wxPanel* leftSplitterPanel;
    wxPanel* tabitemProperties;
    wxTreeCtrl* treectrlItems;
    wxPanel* tabitemProject;
    //wxListCtrl* lstbxModels;
    //wxPanel* tabitemModels;
    wxNotebook* tabConfiguration;
    wxPanel* rightSplitterPanel;
    wxSplitterWindow* mainSplitter;
    // end wxGlade
}; // wxGlade: end class


#endif // WXIRCEMAINWINDOW_H

