
// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Jul 09 19:43:48 2006
#ifndef WXIRCEMENUBAR_H
#define WXIRCEMENUBAR_H

enum wxIRCEMenuBar_States
{
  NO_PROJECT_CREATED,
  PROJECT_CREATED,
  CONFIGURATION_SELECTED,
  VIRTUAL_WORLD_SELECTED,
  CLIENT_CONTROL_SELECTED
};

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

class wxIRCEMenuBar: public wxMenuBar {
public:
    // begin wxGlade: wxIRCEMenuBar::ids
    // end wxGlade
    wxIRCEMenuBar();
    void SetState(enum wxIRCEMenuBar_States state);    

private:
    // begin wxGlade: wxIRCEMenuBar::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxIRCEMenuBar::attributes
    // end wxGlade
}; // wxGlade: end class

enum WXIRCEMENUBAR_MESSAGES
{
  // Menu Project
  NEW_PROJECT_MENU = 100,
  EDIT_PROJECT_MENU,
  LOAD_PROJECT_MENU,
  SAVE_PROJECT_MENU,
  SIMULATE_PROJECT_MENU,
  TRANSFER_CONTROL_MENU,
  ABOUT_MENU,
  EXIT_MENU,
  // Menu World File
  NEW_WORLD_FILE,
  CLEAN_VIRTUAL_WORLD,
  LOAD_WORLD_FILE,
  SAVE_WORLD_FILE,
  ADD_3D_MODEL,
  REMOVE_3D_MODEL,
  SELECT_3D_MODEL,
  ADD_CHILD_MODEL,
  REMOVE_CHILD_MODEL,
  // Menu Control Program
  NEW_CONTROL_PROGRAM,
  LOAD_CONTROL_PROGRAM,
  SAVE_CONTROL_PROGRAM,
  REMOVE_CONTROL_PROGRAM,
  COMPILE_CONTROL_PROGRAM,
  // Menu Configuration Files
  NEW_CONFIGURATION_FILE,
  LOAD_CONFIGURATION_FILE,
  SAVE_CONFIGURATION_FILE,
  REMOVE_CONFIGURATION_FILE
};


#endif // WXIRCEMENUBAR_H


