// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Dec 03 23:00:07 2006
#ifndef WXIRCECONFIGURATIONDIALOG_H
#define WXIRCECONFIGURATIONDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

class wxIRCEConfigurationDialog: public wxDialog {
public:
    // begin wxGlade: wxIRCEConfigurationDialog::ids
    // end wxGlade

    wxIRCEConfigurationDialog(wxWindow* parent,wxWindowID id,const wxString& title);

private:
    // begin wxGlade: wxIRCEConfigurationDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

public:
    // begin wxGlade: wxIRCEConfigurationDialog::attributes
    wxStaticText* lbPlayerPath;
    wxTextCtrl* txtPlayerPath;
    wxStaticText* lbGazeboPath;
    wxTextCtrl* txtGazeboPath;
    wxStaticText* lbCPPCompilerPath;
    wxTextCtrl* txtCPPCompilerPath;
    wxStaticText* lbPlayerHeaderPath;
    wxTextCtrl* txtPlayerHeaderPath;
    wxStaticText* lbPlayerLibPath;
    wxTextCtrl* txtPlayerLibPath;
    wxButton* btOk;
    wxButton* btCancel;
    // end wxGlade

    void On_BtOk_Clicked(wxCommandEvent& e);
    void On_BtCancel_Clicked(wxCommandEvent& e);

}; // wxGlade: end class


#endif // WXIRCECONFIGURATIONDIALOG_H

