// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Dec 03 22:45:52 2006

#include "wxPlayerConfigurationDialog.h"


wxPlayerConfigurationDialog::wxPlayerConfigurationDialog(wxWindow* parent,wxWindowID id,const wxString& title,VirtualWorld * virtualWorld):
    wxDialog(parent, id, title)
{
    // begin wxGlade: wxPlayerConfigurationDialog::wxPlayerConfigurationDialog
    lbName = new wxStaticText(this, -1, wxT("Name"),wxPoint(5,5));
    txtName = new wxTextCtrl(this, -1, wxT(""),wxPoint(105,5));
    lbProvides = new wxStaticText(this, -1, wxT("Provides"),wxPoint(5,25));
    txtProvides = new wxTextCtrl(this, -1, wxT(""),wxPoint(105,25));
    lbGzId = new wxStaticText(this, -1, wxT("Gz_Id"),wxPoint(5,45));
    cmbbxGzId = new wxComboBox(this, -1, wxT(""), wxPoint(105,45), wxDefaultSize, 0, NULL, wxCB_DROPDOWN);
    btOk = new wxButton(this, id+1, wxT("Ok"),wxPoint(5,65));
    btCancel = new wxButton(this, id+2, wxT("Cancel"),wxPoint(105,65));

    set_properties();
    do_layout();
    // end wxGlade

    // Passa os Ids do modelos no array para o combobox
    for(unsigned int i=0;i < virtualWorld->GetNumModels(); i++)
    {
      Model * model = virtualWorld->GetModels()[i];
      this->cmbbxGzId->Append( wxString( model->GetId() ) );
    }

        // Ligacao de eventos
    wxEvtHandler::Connect(id+1,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxPlayerConfigurationDialog::On_BtOk_Clicked );
    wxEvtHandler::Connect(id+2,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxPlayerConfigurationDialog::On_BtCancel_Clicked );  

}


void wxPlayerConfigurationDialog::set_properties()
{
    // begin wxGlade: wxPlayerConfigurationDialog::set_properties
    SetTitle(wxT("Player Configuration Dialog"));
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
    txtName->SetSize(wxSize(120, -1));
    txtProvides->SetSize(wxSize(120, -1));
    cmbbxGzId->SetSize(wxSize(150, -1));
    // end wxGlade   
    this->SetSize(wxSize(270,130));
}


void wxPlayerConfigurationDialog::do_layout()
{
    // begin wxGlade: wxPlayerConfigurationDialog::do_layout
    //wxGridSizer* sizerMain = new wxGridSizer(4, 2, 0, 0); //(4,2,0,0)
    //sizerMain->Add(lbName, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(txtName, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(lbProvides, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(txtProvides, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(lbGzId, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(cmbbxGzId, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(btOk, 0, wxADJUST_MINSIZE, 0);
    //sizerMain->Add(btCancel, 0, wxADJUST_MINSIZE, 0);
    //SetAutoLayout(true);
    //SetSizer(sizerMain);
    //sizerMain->Fit(this);
    //sizerMain->SetSizeHints(this);
    Layout();
    // end wxGlade
}

void wxPlayerConfigurationDialog::On_BtOk_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetReturnCode(wxID_OK);  
}

void wxPlayerConfigurationDialog::On_BtCancel_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetModal(wxID_CANCEL);
}
