// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Dec 03 22:45:52 2006
#ifndef WXPLAYERCONFIGURATIONDIALOG_H
#define WXPLAYERCONFIGURATIONDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade

#include <vector>
#include "Model.hh"
#include "VirtualWorld.h"

using namespace std;

class wxPlayerConfigurationDialog: public wxDialog {
public:
    // begin wxGlade: wxPlayerConfigurationDialog::ids
    // end wxGlade

  wxPlayerConfigurationDialog(wxWindow* parent,wxWindowID id,const wxString& title,VirtualWorld * virtualWorld);

private:
    
    VirtualWorld * virtualWorld;
    // begin wxGlade: wxPlayerConfigurationDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

public:
    // begin wxGlade: wxPlayerConfigurationDialog::attributes
    wxStaticText* lbName;
    wxTextCtrl* txtName;
    wxStaticText* lbProvides;
    wxTextCtrl* txtProvides;
    wxStaticText* lbGzId;
    wxComboBox* cmbbxGzId;
    wxButton* btOk;
    wxButton* btCancel;
    // end wxGlade

    void On_BtOk_Clicked(wxCommandEvent& e);
    void On_BtCancel_Clicked(wxCommandEvent& e);

}; // wxGlade: end class


#endif // WXPLAYERCONFIGURATIONDIALOG_H

