// -*- C++ -*- generated by wxGlade 0.4.1 on Sun Dec 03 23:00:07 2006

#include "wxSimulationConfigurationDialog.h"


wxSimulationConfigurationDialog::wxSimulationConfigurationDialog(wxWindow* parent,wxWindowID id,const wxString& title):
    wxDialog(parent, id, title) 
{
    // begin wxGlade: wxSimulationConfigurationDialog::wxSimulationConfigurationDialog
    lbName = new wxStaticText(this, -1, wxT("Name"));
    txtName = new wxTextCtrl(this, -1, wxT(""));
    lbProvides = new wxStaticText(this, -1, wxT("Provides"));
    txtProvides = new wxTextCtrl(this, -1, wxT(""));
    lbPlugIn = new wxStaticText(this, -1, wxT("Plug-In"));
    txtPlugIn = new wxTextCtrl(this, -1, wxT(""));
    lbServerId = new wxStaticText(this, -1, wxT("Server_Id"));
    txtServerId = new wxTextCtrl(this, -1, wxT(""));
    btOk = new wxButton(this, id+1, wxT("Ok"));
    btCancel = new wxButton(this, id+2, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade

    wxEvtHandler::Connect(id+1,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxSimulationConfigurationDialog::On_BtOk_Clicked );
    wxEvtHandler::Connect(id+2,wxEVT_COMMAND_BUTTON_CLICKED,
                  (wxObjectEventFunction) (wxEventFunction) (wxCommandEventFunction)
                  &wxSimulationConfigurationDialog::On_BtCancel_Clicked );  

}


void wxSimulationConfigurationDialog::set_properties()
{
    // begin wxGlade: wxSimulationConfigurationDialog::set_properties
    SetTitle(wxT("Simulation Configuration Dialog"));
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
    txtName->SetSize(wxSize(200, 21));
    txtProvides->SetSize(wxSize(200, 21));
    txtPlugIn->SetSize(wxSize(200, 21));
    txtServerId->SetSize(wxSize(200, 21));
    // end wxGlade
}


void wxSimulationConfigurationDialog::do_layout()
{
    // begin wxGlade: wxSimulationConfigurationDialog::do_layout
    wxGridSizer* sizerMain = new wxGridSizer(5, 2, 0, 0);
    sizerMain->Add(lbName, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtName, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbProvides, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtProvides, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbPlugIn, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtPlugIn, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(lbServerId, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(txtServerId, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(btOk, 0, wxADJUST_MINSIZE, 0);
    sizerMain->Add(btCancel, 0, wxADJUST_MINSIZE, 0);
    SetAutoLayout(true);
    SetSizer(sizerMain);
    sizerMain->Fit(this);
    sizerMain->SetSizeHints(this);
    Layout();
    // end wxGlade
}

void wxSimulationConfigurationDialog::On_BtOk_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetReturnCode(wxID_OK);
}

void wxSimulationConfigurationDialog::On_BtCancel_Clicked(wxCommandEvent& e)
{
  this->Close();
  this->SetModal(wxID_CANCEL);
}
